site_name: Корпоративный styleguide для python
docs_dir: docs/
repo_name: 'Dihset/python-corporate-styleguide'
repo_url: 'https://github.com/Dihset/python-corporate-styleguide'
nav:
  - Введение: index.md
  - Матрица компетенций: 
    - Python Backend: 'competency-matrix/python-backend.md'
theme:
  name: material
plugins:
  - table-reader